spring:
  #redis 集群配置
  redis:
    host: 172.19.167.222
    port: 26380
    password: dkjnfd*32409
    timeout: 12000
    database: 0
    lettuce:
      pool:
        max-active: 100  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 6 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）